version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo Installing AWS SAM CLI...
      - pip install aws-sam-cli
  build:
    commands:
      - echo Build started on `date`
      - dotnet build
      - sam build
      - sam package \
          --s3-bucket my-artifacts-bucket \
          --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml
